version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "8888:8888"
    volumes:
      - .:/conflictproxyindicators
    command:
      - sh
      - -c
      - tail -f /dev/null